### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by lmckiwo** [lmckiwo/alive#13]
2019-11-05 09:56:01,116 INFO  ATIC.status.readJson._connect() ATIC-005[SMM] already connected
2019-11-05 09:56:07,621 INFO  ATIC.status.readJson._connect() ATIC-005[SMM] already connected
2019-11-05 09:56:46,216 INFO  ATIC.status.readJson._connect() ATIC-005[SMM] already connected
2019-11-05 09:56:51,239 INFO  ATIC.statusHandler.1.writeStatus() Updating ATIC-005-SMM from connected => notConnected
Traceback (most recent call last):
  File "test3.py", line 16, in <module>
    hosts.updateAllVendorNodesStatus("ENSCO")
  File "/home/188209/dev/alive3.2.2/alive/ATICHosts.py", line 234, in updateAllVendorNodesStatus
    if self.isVendorNodeAlive(car, node, vendor):
  File "/home/188209/dev/alive3.2.2/alive/ATICHosts.py", line 411, in isVendorNodeAlive
    return self.ping(ip=ip, car=car, gwNode=gwNode)
  File "/home/188209/dev/alive3.2.2/alive/ATICHosts.py", line 247, in ping
    theOS = self.getOS(host=car, node=gwNode)
  File "/home/188209/dev/alive3.2.2/alive/ATICHosts.py", line 113, in getOS
    output, err = self.runCommand(host, node, "uname", printOut=True)
TypeError: 'bool' object is not iterable
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.119:22] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.119:30254] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.119:30011] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.119:30002] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.119:30007] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.127:22] closed.
2019-11-05 09:56:51,286 INFO  ATIC.paramikoWrapper.1.__del__() [10.184.2.127:30254] closed.

**Comment by lmckiwo** [comment]
The problem is with _getOS()


    def _getOS(self, host=None, node="SMM"):
        if host is None:
            hostOS = subprocess.Popen(['uname'], stdout=subprocess.PIPE).stdout.read().decode('utf-8').strip('\n')
            if str(hostOS.lower()).startswith("cygwin"):
                return "CYGWIN"
            if str(hostOS.lower()).startswith('linux'):
                return "Linux"
        else:
            # output, err = self.runCommand(host, node, "uname", printOut=True)
            **out = self.runCommand(host, node, "uname", printOut=True)
            if len(out) == 1:
                return out
            else:
                output = out[0]
                err = out[1]**

The bolded part of the code was an attempt to correct the problem.

But to fix it properly, the fix should be done within runCommand()

**Comment by lmckiwo** [comment]
Made correction in runCommand()
